### PR TITLE
Update project.cmt

### PR DESCRIPTION
**Pull request by mesmith75**
Remove LHCBDIRAC.

### CODE REVIEW

**Comment by rob-c** [comment]
Does the LHCb install still work in this case?
I imagine Ganga will likely be asked to update in the future to support the cmake style of project setup but for now if we can drop this things get a bit easier. However, we don't get the LCG version of Python or ROOT which could potentially cause problems for some users. Do we need to modify the env defaults for LHCb to point to the LCG ROOT install in this case?

**Comment by mesmith75** [comment]
My install works - although I haven't tried a clean install.
Yes, I guess we need to sort out the LCG and ROOT versions properly before we get rid of all the CMT stuff.

**Comment by rob-c** [comment]
After looking at possible failures for the LHCb install this will likely be fixed by fixing/removing the LHCbDirac dependency. I suggest we merge this ahead of 6.3.0 and if you poke me tomorrow I'll fix the tags in this repo to allow the install script to pick up the correct version during the install.
I say we rip off the bandaid and merge this we will be able to fix ROOT problems by changing config vars.

**Comment by rob-c** [comment]
Any objections to me merging this and making the v603r0 tags?

**Comment by rob-c** [comment]
DO NOT ATTEMPT AN LHCB SOFTWARE INSTALL ATM, THIS HAS BROKEN SOMETHING

**Comment by rob-c** [comment]
OK, this __should__ be fixed now.
FYI: This should __NOT__ have ever worked as it required the LCG ROOT which we explicitly pull in through the LHCbDirac. I've removed this from our deps so we now startup with whatever ROOT (if any) the user has defined in their config or in the env.
This may effect users going forward but we can deal with this now that we dynamically pull in the LHCbDirac env in a nicer way.

**Comment by mesmith75** [comment]
@rob-c Thanks for sorting that - I forgot to say I had to remove the LCG ROOT dependencies as well.

**Pull request merged**
